trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildStage
    displayName: Build Stage
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'
        - task: CmdLine@2
          inputs:
            script: 'npm install'
        - task: CmdLine@2
          inputs:
            script: 'npm run build'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'Application'
            publishLocation: 'Container'